import type { Metadata } from "next";
import { Inter, Jost} from "next/font/google";
import "./globals.css";

import SessionProvider from "./components/providers/SessionProvider";
import ThemeProvider from "./components/providers/ThemeProvider";
import Footer from "./components/Footer";
import Topbar from "./components/Topbar";
const inter = Inter({ subsets: ["latin"] });
const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <ThemeProvider>
          <SessionProvider>
            <Topbar />
            <div className="min-h-[calc(100%-80px)]">{children}</div>
            <Footer />
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
